# Copyright 2025 Center for Digital Humanities, Princeton University
# SPDX-License-Identifier: Apache-2.0

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: local
    hooks:
      - id: check-copyright
        name: check-copyright
        entry: python scripts/add_copyright.py --check
        language: python
