language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -e .
  - pip install 'neuxml[dev]'
  - pip install coveralls

script:
  - nosetests --with-coverage

after_success:
  - coveralls
