language: python

python:
  - "3.12"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -e .
  - pip install 'neuxml[dev]'
  - pip install coveralls

script:
  - pytest --cov=./ --cov-report=xml
  
after_success:
  - coveralls
