language: python
python:
  - "2.7"
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - "pip install -e . --use-mirrors"
  - "pip install 'eulxml[dev]' --use-mirrors"
# command to run tests, e.g. python setup.py test
# - schema loading currently requires an HTTP PROXY; cheat and set an empty proxy
script: env HTTP_PROY= nosetests
